// <auto-generated />
using System;
using ConsultaPessoas.Application.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsultaPessoas.Application.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("main.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f641b7e8-616d-4297-a650-c135a11fcbb4"),
                            Cpf = "27476834275",
                            DataNascimento = new DateTime(1982, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maitê"
                        },
                        new
                        {
                            Id = new Guid("c6504ce0-7b3c-466f-af10-77baa3cddbc3"),
                            Cpf = "84174064768",
                            DataNascimento = new DateTime(2011, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernanda"
                        },
                        new
                        {
                            Id = new Guid("0c312fbc-fad7-4e2a-a37e-d179640baeb1"),
                            Cpf = "95475573433",
                            DataNascimento = new DateTime(1920, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Vinícius"
                        },
                        new
                        {
                            Id = new Guid("7b32f0c8-d2ed-4199-b359-57e51fbffe83"),
                            Cpf = "26761868505",
                            DataNascimento = new DateTime(1980, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Laura"
                        },
                        new
                        {
                            Id = new Guid("0f3ecea2-f6a7-4542-a35f-d810176c778b"),
                            Cpf = "42341902928",
                            DataNascimento = new DateTime(1947, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Arthur"
                        },
                        new
                        {
                            Id = new Guid("b9e2d903-2529-483f-8e64-0eeb9e0abb2e"),
                            Cpf = "16585444981",
                            DataNascimento = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Eloá"
                        },
                        new
                        {
                            Id = new Guid("7b07000f-ce05-4be1-bfe4-c507cfad941c"),
                            Cpf = "30368961397",
                            DataNascimento = new DateTime(1981, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Malu"
                        },
                        new
                        {
                            Id = new Guid("98a6ebd7-4364-4059-95f2-3eb9e6473ebe"),
                            Cpf = "28368431280",
                            DataNascimento = new DateTime(1966, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Antônia"
                        },
                        new
                        {
                            Id = new Guid("114341d4-9114-4f24-b913-b161e493dc85"),
                            Cpf = "78415285906",
                            DataNascimento = new DateTime(1937, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sophia"
                        },
                        new
                        {
                            Id = new Guid("bcac5ea1-7ac7-40e4-86bf-6a7d830d5583"),
                            Cpf = "90671564935",
                            DataNascimento = new DateTime(1957, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Eduarda"
                        },
                        new
                        {
                            Id = new Guid("ca087f84-6c5d-4554-865b-bde99835ef7e"),
                            Cpf = "52564830480",
                            DataNascimento = new DateTime(1999, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Agatha"
                        },
                        new
                        {
                            Id = new Guid("0c16f010-5a1a-4459-ba0c-b709f524dd20"),
                            Cpf = "85536522035",
                            DataNascimento = new DateTime(1938, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Analu"
                        },
                        new
                        {
                            Id = new Guid("3e0019ec-41b3-4376-a529-8e1defb51cae"),
                            Cpf = "37760953771",
                            DataNascimento = new DateTime(1980, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Analu"
                        },
                        new
                        {
                            Id = new Guid("333243f1-b6f2-449f-b198-a0554a6faa4a"),
                            Cpf = "73559629810",
                            DataNascimento = new DateTime(1922, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Eloá"
                        },
                        new
                        {
                            Id = new Guid("4808358d-cace-4c9f-af76-c2f08c1a6aec"),
                            Cpf = "60900206802",
                            DataNascimento = new DateTime(1997, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Emanuelly"
                        },
                        new
                        {
                            Id = new Guid("984b4c0d-9514-4f0f-acba-c83e3d50de77"),
                            Cpf = "54769343329",
                            DataNascimento = new DateTime(1931, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Thiago"
                        },
                        new
                        {
                            Id = new Guid("fdd6b6c6-c7ad-4ac8-8548-26cfd2006a64"),
                            Cpf = "31408900360",
                            DataNascimento = new DateTime(1984, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = new Guid("b7e68764-bd49-438d-90b9-11dec6bea908"),
                            Cpf = "68839984542",
                            DataNascimento = new DateTime(2012, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Elisa"
                        },
                        new
                        {
                            Id = new Guid("918705d3-c511-4a73-9158-8d9a9d0dd6f2"),
                            Cpf = "20792689968",
                            DataNascimento = new DateTime(1984, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Heitor"
                        },
                        new
                        {
                            Id = new Guid("25c30132-48d6-4ba3-ba12-7820d4084cb2"),
                            Cpf = "30340145200",
                            DataNascimento = new DateTime(1997, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Amanda"
                        },
                        new
                        {
                            Id = new Guid("c522e2b1-cdac-4c39-a51b-f006c7cab3b1"),
                            Cpf = "64908291934",
                            DataNascimento = new DateTime(1991, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Davi"
                        },
                        new
                        {
                            Id = new Guid("25de9f3b-fcf3-493d-b8bd-403ecaec34da"),
                            Cpf = "36362686608",
                            DataNascimento = new DateTime(1983, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gael"
                        },
                        new
                        {
                            Id = new Guid("310a33fa-0406-4531-8854-4d2d7ff03cfc"),
                            Cpf = "79816586916",
                            DataNascimento = new DateTime(1974, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Isis"
                        },
                        new
                        {
                            Id = new Guid("feaf9ac6-4235-448c-826c-e964f0f327f1"),
                            Cpf = "36038737006",
                            DataNascimento = new DateTime(1976, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Elisa"
                        },
                        new
                        {
                            Id = new Guid("423e1ab9-da1f-490e-86ba-9e371b2b6ab5"),
                            Cpf = "17639851211",
                            DataNascimento = new DateTime(2000, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "André"
                        },
                        new
                        {
                            Id = new Guid("0345087e-9a39-4742-9e69-8501f3762a1d"),
                            Cpf = "43580748475",
                            DataNascimento = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Murilo"
                        },
                        new
                        {
                            Id = new Guid("66b995c0-5cc1-45c8-986a-de0c95ad0bc5"),
                            Cpf = "16917694100",
                            DataNascimento = new DateTime(1986, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Luiza"
                        },
                        new
                        {
                            Id = new Guid("c4acf8f4-1d77-4738-83d7-2266daef1f2a"),
                            Cpf = "26800169986",
                            DataNascimento = new DateTime(1993, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Oliver"
                        },
                        new
                        {
                            Id = new Guid("847c44ea-42e3-453a-8a7d-4d398e3094ba"),
                            Cpf = "69585180553",
                            DataNascimento = new DateTime(2014, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Heitor"
                        },
                        new
                        {
                            Id = new Guid("348ba73c-be04-48e3-b3f9-50d3b373b719"),
                            Cpf = "74121619544",
                            DataNascimento = new DateTime(1972, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Augusto"
                        },
                        new
                        {
                            Id = new Guid("6f21fa16-07a5-4543-9bd1-876402f5b31f"),
                            Cpf = "30932917631",
                            DataNascimento = new DateTime(1995, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Noah"
                        },
                        new
                        {
                            Id = new Guid("a31a251a-9fc0-47a6-b200-191d7a082390"),
                            Cpf = "14166291734",
                            DataNascimento = new DateTime(1985, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Kaique"
                        },
                        new
                        {
                            Id = new Guid("3d30365b-810a-40c7-811b-5df15159654e"),
                            Cpf = "97577883255",
                            DataNascimento = new DateTime(1953, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("221cdf32-9e29-4416-9ed8-b0465866d272"),
                            Cpf = "17592182432",
                            DataNascimento = new DateTime(2000, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Mirella"
                        },
                        new
                        {
                            Id = new Guid("7a608767-131b-4f31-9ca5-d0db46625026"),
                            Cpf = "60283007303",
                            DataNascimento = new DateTime(2015, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernanda"
                        },
                        new
                        {
                            Id = new Guid("898adeb1-5eed-4bb6-830c-1cca4bc0d898"),
                            Cpf = "91845117379",
                            DataNascimento = new DateTime(1939, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pietro"
                        },
                        new
                        {
                            Id = new Guid("a2f7495a-86f4-47b1-b5d4-35d0f2914f76"),
                            Cpf = "59260024358",
                            DataNascimento = new DateTime(1925, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Leonardo"
                        },
                        new
                        {
                            Id = new Guid("96f70053-d4da-4584-a695-a89115d14dee"),
                            Cpf = "71749658658",
                            DataNascimento = new DateTime(2002, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Benício"
                        },
                        new
                        {
                            Id = new Guid("826eacfc-a963-4908-9a40-72456012625b"),
                            Cpf = "50235302210",
                            DataNascimento = new DateTime(1938, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Manuela"
                        },
                        new
                        {
                            Id = new Guid("b41e57cf-ac0e-4d75-bee7-f587439b9493"),
                            Cpf = "39295867203",
                            DataNascimento = new DateTime(2016, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Emilly"
                        },
                        new
                        {
                            Id = new Guid("8a45d9a2-d907-4b87-9822-ce8523cd9fef"),
                            Cpf = "24495264982",
                            DataNascimento = new DateTime(2021, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gabriela"
                        },
                        new
                        {
                            Id = new Guid("0fec9114-f7e2-4250-91d5-e068e0746c93"),
                            Cpf = "89214654484",
                            DataNascimento = new DateTime(2000, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Matheus"
                        },
                        new
                        {
                            Id = new Guid("6fd201ab-0c27-4e47-a249-63049aa456bb"),
                            Cpf = "70578137836",
                            DataNascimento = new DateTime(1958, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rafael"
                        },
                        new
                        {
                            Id = new Guid("c752d69d-b082-47be-a548-4485d9bfdfaa"),
                            Cpf = "78218089705",
                            DataNascimento = new DateTime(1997, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Henrique"
                        },
                        new
                        {
                            Id = new Guid("b167aa87-7c1d-47da-8d77-8ca2119b63e5"),
                            Cpf = "79741065574",
                            DataNascimento = new DateTime(1930, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Martin"
                        },
                        new
                        {
                            Id = new Guid("e4e4c086-5ce3-4309-8533-5e515acf5220"),
                            Cpf = "99937967430",
                            DataNascimento = new DateTime(1950, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Felipe"
                        },
                        new
                        {
                            Id = new Guid("d238701c-ca6e-4151-9833-aa9dac770be1"),
                            Cpf = "51307437095",
                            DataNascimento = new DateTime(2008, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cauã"
                        },
                        new
                        {
                            Id = new Guid("438ba9c0-dc50-4154-8bf7-b5508fd5a115"),
                            Cpf = "41525832077",
                            DataNascimento = new DateTime(1924, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Isabel"
                        },
                        new
                        {
                            Id = new Guid("64898525-8d6d-4379-8847-2f455dad164a"),
                            Cpf = "16336208400",
                            DataNascimento = new DateTime(1931, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Felipe"
                        },
                        new
                        {
                            Id = new Guid("e2d89b9e-42bd-43cc-8a40-1b758c10e44d"),
                            Cpf = "68891915955",
                            DataNascimento = new DateTime(2012, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "André"
                        },
                        new
                        {
                            Id = new Guid("6a4b1fae-6e03-4211-bf13-d5fa1b632f40"),
                            Cpf = "84029426875",
                            DataNascimento = new DateTime(1993, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pietro"
                        },
                        new
                        {
                            Id = new Guid("a1807c83-07c6-4849-9a99-2561cdc5e2f9"),
                            Cpf = "12713503787",
                            DataNascimento = new DateTime(1927, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pedro"
                        },
                        new
                        {
                            Id = new Guid("9ac2e2b6-6bb0-45fb-b22a-6eaa6c9a39ba"),
                            Cpf = "20290670241",
                            DataNascimento = new DateTime(2016, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Helena"
                        },
                        new
                        {
                            Id = new Guid("7b41ab6c-ec9a-4a7f-938d-9f125d76f844"),
                            Cpf = "66476041703",
                            DataNascimento = new DateTime(1991, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Beatriz"
                        },
                        new
                        {
                            Id = new Guid("c5fc2e4d-a9a0-4aeb-a0ba-e45831bd422a"),
                            Cpf = "99969304160",
                            DataNascimento = new DateTime(2006, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Felipe"
                        },
                        new
                        {
                            Id = new Guid("f089611f-6755-4c6c-b9e8-bbc50fd3dbe2"),
                            Cpf = "71611693560",
                            DataNascimento = new DateTime(1960, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ian"
                        },
                        new
                        {
                            Id = new Guid("fe587ad5-f16b-4a15-bdcc-5943ce4d44d0"),
                            Cpf = "99642111551",
                            DataNascimento = new DateTime(2009, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pedro"
                        },
                        new
                        {
                            Id = new Guid("ea814626-4088-4cf7-bbe9-b24341bd754c"),
                            Cpf = "49916439966",
                            DataNascimento = new DateTime(1933, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernando"
                        },
                        new
                        {
                            Id = new Guid("4ac6df8d-860c-40be-9254-0f366fb933ba"),
                            Cpf = "57126138679",
                            DataNascimento = new DateTime(2003, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Breno"
                        },
                        new
                        {
                            Id = new Guid("760abbcd-2734-4627-8597-403619ee059d"),
                            Cpf = "46572225119",
                            DataNascimento = new DateTime(1983, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maitê"
                        },
                        new
                        {
                            Id = new Guid("5f58d3d7-ad31-4cdd-b78a-f14c23a9a64e"),
                            Cpf = "15270628309",
                            DataNascimento = new DateTime(1993, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("7f0d001b-549e-46dc-9b09-b7567042814c"),
                            Cpf = "78930685668",
                            DataNascimento = new DateTime(1982, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Francisco"
                        },
                        new
                        {
                            Id = new Guid("5fbeda90-6438-4828-a1c2-64f8e368ac53"),
                            Cpf = "32772682846",
                            DataNascimento = new DateTime(1942, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Levi"
                        },
                        new
                        {
                            Id = new Guid("05249613-665b-4308-966d-205b976153bb"),
                            Cpf = "99563548728",
                            DataNascimento = new DateTime(2003, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pedro"
                        },
                        new
                        {
                            Id = new Guid("7e98e468-8d23-49dd-9223-1dfc6f6656d3"),
                            Cpf = "23510535839",
                            DataNascimento = new DateTime(2017, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "José"
                        },
                        new
                        {
                            Id = new Guid("1c7b8413-3303-4030-a1f9-cfd3abcf3741"),
                            Cpf = "36252310344",
                            DataNascimento = new DateTime(1924, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Milena"
                        },
                        new
                        {
                            Id = new Guid("dbc7a423-1845-429a-ac5c-de08e4b98558"),
                            Cpf = "32955525251",
                            DataNascimento = new DateTime(1968, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Raul"
                        },
                        new
                        {
                            Id = new Guid("93dba988-ddf8-4895-b38f-593d6d263d51"),
                            Cpf = "63320533053",
                            DataNascimento = new DateTime(1976, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Louise"
                        },
                        new
                        {
                            Id = new Guid("258f5834-3ce1-4149-a98e-6dd94c5d9e71"),
                            Cpf = "57599842179",
                            DataNascimento = new DateTime(1973, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Júlia"
                        },
                        new
                        {
                            Id = new Guid("1148d316-4575-4e05-b64c-0e049cde8791"),
                            Cpf = "90904857590",
                            DataNascimento = new DateTime(1941, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Allana"
                        },
                        new
                        {
                            Id = new Guid("26019cdd-86b8-4868-8e5b-26a27646ae8a"),
                            Cpf = "49176366472",
                            DataNascimento = new DateTime(1962, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Arthur"
                        },
                        new
                        {
                            Id = new Guid("718518b6-2179-4c96-ba43-4fdea60a31e4"),
                            Cpf = "79895935307",
                            DataNascimento = new DateTime(1923, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lara"
                        },
                        new
                        {
                            Id = new Guid("8e01a0a4-ad6a-4d11-bbf2-44b189face2d"),
                            Cpf = "52703430531",
                            DataNascimento = new DateTime(1961, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Valentina"
                        },
                        new
                        {
                            Id = new Guid("97078218-fd60-47aa-8d58-8698e638d39d"),
                            Cpf = "82536604640",
                            DataNascimento = new DateTime(1979, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Matheus"
                        },
                        new
                        {
                            Id = new Guid("6cafdac9-8a8f-49d0-a0ab-da7a47da34b7"),
                            Cpf = "27483949767",
                            DataNascimento = new DateTime(1980, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Laura"
                        },
                        new
                        {
                            Id = new Guid("834331a6-4742-436f-b665-0d43a5fe460a"),
                            Cpf = "60529120577",
                            DataNascimento = new DateTime(1952, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Milena"
                        },
                        new
                        {
                            Id = new Guid("64f007d2-6aef-45b9-b5bf-55953955c018"),
                            Cpf = "83063777960",
                            DataNascimento = new DateTime(2018, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Arthur"
                        },
                        new
                        {
                            Id = new Guid("188b7992-48eb-4d20-aa4f-90be0be9f674"),
                            Cpf = "57491251650",
                            DataNascimento = new DateTime(1937, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Danilo"
                        },
                        new
                        {
                            Id = new Guid("576b6cca-b563-4a78-8775-3ae98ff06b67"),
                            Cpf = "44040813839",
                            DataNascimento = new DateTime(1965, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pietro"
                        },
                        new
                        {
                            Id = new Guid("cfad0310-3e5e-477c-a993-f8e28f68dad3"),
                            Cpf = "57149739172",
                            DataNascimento = new DateTime(1990, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Benício"
                        },
                        new
                        {
                            Id = new Guid("6ca9aa31-8ce2-49d8-8caa-a2ac2b4185ce"),
                            Cpf = "55414726957",
                            DataNascimento = new DateTime(1995, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Vinícius"
                        },
                        new
                        {
                            Id = new Guid("0cd138d4-31e1-4d66-ae6e-e3e7dcd75b72"),
                            Cpf = "46041087220",
                            DataNascimento = new DateTime(1995, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Malu"
                        },
                        new
                        {
                            Id = new Guid("578583e3-7875-46ab-91ea-30df6be60d63"),
                            Cpf = "19196256745",
                            DataNascimento = new DateTime(1984, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Antonella"
                        },
                        new
                        {
                            Id = new Guid("ac2cd9ee-2ebb-42d4-b961-f1e2c50f3272"),
                            Cpf = "86389340842",
                            DataNascimento = new DateTime(1948, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carolina"
                        },
                        new
                        {
                            Id = new Guid("381cd3c9-34a2-4f56-9c9a-998bcb919cdd"),
                            Cpf = "40430801319",
                            DataNascimento = new DateTime(1984, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Davi"
                        },
                        new
                        {
                            Id = new Guid("a35607f3-8956-465e-b2e9-1b1acecedb05"),
                            Cpf = "10569002613",
                            DataNascimento = new DateTime(2001, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Guilherme"
                        },
                        new
                        {
                            Id = new Guid("09fbdc12-9179-444b-9216-afe876d7ff58"),
                            Cpf = "25871804730",
                            DataNascimento = new DateTime(1977, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Felipe"
                        },
                        new
                        {
                            Id = new Guid("17ce30c3-cefa-4886-9d9c-3a25b491b4cd"),
                            Cpf = "56743822124",
                            DataNascimento = new DateTime(2005, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Daniel"
                        },
                        new
                        {
                            Id = new Guid("7836a3b6-22f3-44d9-9748-342abcfd401b"),
                            Cpf = "70213017156",
                            DataNascimento = new DateTime(2016, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Heloísa"
                        },
                        new
                        {
                            Id = new Guid("045321b9-ea76-4bbc-a79d-f46e051f6351"),
                            Cpf = "90228376106",
                            DataNascimento = new DateTime(1927, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Amanda"
                        },
                        new
                        {
                            Id = new Guid("b9f824f6-50f8-4d2e-a663-75b74e81988b"),
                            Cpf = "69731803882",
                            DataNascimento = new DateTime(1923, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Heloise"
                        },
                        new
                        {
                            Id = new Guid("122f69c5-c24b-4464-a935-1b0690230e17"),
                            Cpf = "86943615157",
                            DataNascimento = new DateTime(2002, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cecília"
                        },
                        new
                        {
                            Id = new Guid("1d49b239-85ba-4ef8-a676-bc78809fd7fe"),
                            Cpf = "30447442023",
                            DataNascimento = new DateTime(1968, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Joaquim"
                        },
                        new
                        {
                            Id = new Guid("5763994e-d513-4445-b0de-d4f3961b8a65"),
                            Cpf = "81487293445",
                            DataNascimento = new DateTime(1996, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Benício"
                        },
                        new
                        {
                            Id = new Guid("4e2410e9-898f-4789-a486-038f455e5de6"),
                            Cpf = "92105027792",
                            DataNascimento = new DateTime(2008, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Caio"
                        },
                        new
                        {
                            Id = new Guid("80766add-930e-4e73-acb6-f0c4af16f5bf"),
                            Cpf = "33971278159",
                            DataNascimento = new DateTime(1955, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Larissa"
                        },
                        new
                        {
                            Id = new Guid("a50bfb68-35c4-4be8-9a93-332b85226f1a"),
                            Cpf = "71252047169",
                            DataNascimento = new DateTime(1934, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cecília"
                        },
                        new
                        {
                            Id = new Guid("99b91f6f-1817-4495-bc82-a9f6ff89140b"),
                            Cpf = "81885078579",
                            DataNascimento = new DateTime(1966, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Sophie"
                        },
                        new
                        {
                            Id = new Guid("ae06422b-07f0-454d-9136-dbd98c2c6171"),
                            Cpf = "90933648715",
                            DataNascimento = new DateTime(1994, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Valentina"
                        },
                        new
                        {
                            Id = new Guid("67d339dd-d886-4417-a91c-ba23e7b7a81f"),
                            Cpf = "32460021186",
                            DataNascimento = new DateTime(1981, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Amanda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
